### ISSUE TITLE
แก้ไขเวลาและหมายเลขคำสั่งซื้อ

### ISSUE THREAD

**Issue by LungJane** [iamapinan/WooCommerce-Line-Notify#1]
1 ช่วยแก้ไขเวลาให้เป็นเวลาที่แจ้งจริงด้วยครับ เช่น ในข้อความแจ้ง 04.55 แต่เวลาในเครื่องมัน 11.55 เป็นต้น
2 ช่วยเพิ่มหมายเลขคำสั่งซื้อ เพราะ [order_total] มันแสดงราคารวมของสินค้า

**Comment by iamapinan** [comment]
> 1 ช่วยแก้ไขเวลาให้เป็นเวลาที่แจ้งจริงด้วยครับ เช่น ในข้อความแจ้ง 04.55 แต่เวลาในเครื่องมัน 11.55 เป็นต้น
> 2 ช่วยเพิ่มหมายเลขคำสั่งซื้อ เพราะ [order_total] มันแสดงราคารวมของสินค้า

ข้อ 1 น่าจะเป็น time zone ของเครื่องเราไม่ตรงมากกว่าครับ ให้ลองใส่ `date_default_timezone_set("Asia/Bangkok");` ในไฟล์ functions.php ดู
ข้อ 2 รบกวนอธิบายให้ชัดเจนกว่านี้หน่อยครับ
