### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ellipszist** [iamapinan/WooCommerce-Line-Notify#4]
Message pattern request
- องค์กร (company)
- ลิงก์จัดการออเดอร์ (หลังบ้าน)
- เบอร์โทร
- อีเมล์
- อยากให้เพิ่ม **จังหวัด, รหัสไปรษณีย์, ประเทศ** เข้ามาในรายละเอียด **ที่อยู่ลูกค้า** ด้วยครับ
- บันทึกเพิ่มเติม (order comments)

อยากให้ปรับปรุง
- หากมีการเลือก **จัดส่งไปยังที่อยู่อื่น? (Ship to different address)** ให้อัพเดต **Message pattern (ทั้งหมด)** จาก **billing** ไปที่ **shipping** แทน
- สถานะออเดอร์ (แปลไทยหรือตามภาษาหลักของเวบไซต์)
- รูปภาพ **Add your image url** ไม่ต้องใส่ก็ได้ ปัจจุบันเป็น **required**

**Comment by iamapinan** [comment]
Duplicate of #8 บางส่วนแล้ว
