### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Emilybkk** [iamapinan/WooCommerce-Line-Notify#5]
Error ตรง Notifime Only มีแจ้ง error แบบนี้ในแต่ละตัวเลือก ทุกตัวเลือกขึ้นข้อความเหมือนกันหมด

Warning: in_array() expects parameter 2 to be array, null given in /home/sistermake/domains/sistermakeup.com/public_html/wp-content/plugins/wc_linenotify-master/wc_linenotify.php on line 294

PHP 7.2 WP 4.9.8 Woo 3.4.5

**Comment by Emilybkk** [comment]
ล่าสุดหายแล้ว อยู่ดีๆ ก็ห๊ายยย

**Comment by iamapinan** [comment]
> ล่าสุดหายแล้ว อยู่ดีๆ ก็ห๊ายยย

กำลังดูอยู่เลยว่าแสดงว่า ไม่มีค่าส่งมาครับเลยขึ้นแบบนั้น แต่จริงๆแล้วเราปิดมันได้เหมือนกัน เดี่ยวจะทดสอบให้ดีในคราวถัดไปครับ

**Comment by Emilybkk** [comment]
เหมือนว่าเปลี่ยน token แล้วมันก็หายอ่ะค่ะ
