### ISSUE TITLE
Add your image url ไม่ควรบังคับให้จำเป็นต้องกรอก

### ISSUE THREAD

**Issue by Emilybkk** [iamapinan/WooCommerce-Line-Notify#6]
เนื่องจากเหมือนจะเป็นภาพที่ไม่ได้สื่อถึงอะไรเป็นพิเศษ เช่น ไม่ใช่ภาพของสินค้าที่สั่งซื้อ เข้าใจว่าภาพนี้อาจจะเป็นภาพประจำตัวของร้านเฉยๆ ซึ่งในกรณีที่บางคนอาจจะมีร้านเดียว ซึ่งไม่มีความจำเป็นที่จะต้องใช้รูปภาพเพื่อเป็นจุดสังเกตุ จึงอาจจะไม่จำเป็นต้องระบุภาพนี้ก็ได้ 

หรือถ้าเป็นไปได้ถ้าหากดึงภาพสินค้าได้อัตโนมัติก็น่าจะดีมาก

**Comment by iamapinan** [comment]
จะดำเนินการแก้ไขให้ในรุ่นถัดไปนะครับ ขอบคุณครับ @Emilybkk

**Comment by iamapinan** [comment]
Duplicate of #8
