### ISSUE TITLE
ไม่แสดงเบอร์โทรศัพท์

### ISSUE THREAD

**Issue by Emilybkk** [iamapinan/WooCommerce-Line-Notify#7]
อาจจะเป็นเพราะดึงแค่ address หรือเปล่า มันไม่ดึงฟีลด์เบอร์โทรศัพท์มาด้วย ซึ่งอาจจะจำเป็นในบางธุรกิจหรือช่วยให้ติดต่อลูกค้าได้เลยหากจำเป็นโดยที่ไม่ต้องไปเปิดดูรายละเอียดในเว็บอีกรอบ 

ขอบคุณค่ะ

**Comment by iamapinan** [comment]
update แล้วใน  #[https://github.com/iamapinan/wc_linenotify/tree/v1.0.5](https://github.com/iamapinan/wc_linenotify/tree/v1.0.5)
#8
