### ISSUE TITLE
ดึงชื่อสินค้าได้หรือไม่

### ISSUE THREAD

**Issue by Emilybkk** [iamapinan/WooCommerce-Line-Notify#9]
จากตอนนี้ที่สามารถดึง url ได้ ถ้าจะให้ดึงชื่อสินค้าด้วยจะสะดวกมากขึ้น เช่น 

สินค้าที่สั่งซื้อ : [product_name]

ซึ่งถ้ามีหลายตัวอาจจะสามารถแสดงเป็นลิสต์ได้ เป็นต้น 

ขอบคุณค่ะ

**Comment by iamapinan** [comment]
มีความลำบากในการแสดงผลครับ และไลน์จำกัดตัวอักษรด้วย อาจไม่พอ

**Comment by Emilybkk** [comment]
เพิ่งสังเกตเห็นว่า ตัว [order_url] นี้ไม่ใช่ url ของโปรดักส์ สามารถที่จะดึงเป็น url ของโปรดักส์พอให้ทราบคร่าวๆ ว่าเป็นสินค้าตัวไหนได้มั๊ยคะ ส่วนตัว [order_url] ก็เอาไว้เหมือนเดิมดีแล้ว สำหรับเป็นลิงค์เพื่อจัดการออเดอร์ (ตอนแรกเข้าใจผิดว่าเป็น product url)

ส่วน product_name ถ้ายังไงให้แสดงเพียงบางส่วนก็น่าสนใจนะคะ อาจจะกำหนดตัวอักษร หรือแสดงเป็น sku ของสินค้านั้นๆ แทน เพื่อที่ว่าจะได้ไม่ต้องแสดงข้อความยาวเกินกว่าที่ไลน์จะรับไหว เจ้าของร้านอาจจะตั้ง sku เป็นรหัสเฉพาะให้จำได้ว่าตัวนี้คือสินค้าอะไร 

ขอบคุณค่ะ

**Comment by markvocal** [comment]
ภาพรวมปลั๊กอินนี้ดีมากๆเลยครับ แต่ถ้าเพิ่มชื่อสินค้า หรือ SKU สั้นๆ เป็นรายการ ได้จะดีมากๆเลยครับ

**Comment by iamapinan** [comment]
มาแล้วนะครับ 1.0.6

**Comment by iamapinan** [comment]
> มาแล้วนะครับ 1.0.6
